# Generated by Django 3.0.7 on 2021-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B', 'Beans'), ('D', 'Daal'), ('DS', 'Disposable Stuff'), ('DF', 'Dry Food'), ('FIW', 'Whole Fish'), ('CBF', 'Cleaned Block Fish'), ('K', 'keema'), ('DFS', 'Dry Fish'), ('F', 'Flour'), ('FF', 'Frozen Food'), ('G', 'Ghee'), ('M', 'Meat'), ('O', 'Oil'), ('R', 'Rice'), ('SW', 'Whole Spices'), ('SG', 'Ground Spice'), ('S', 'Sugar'), ('SD', 'Sundries'), ('V', 'Vegetable'), ('P', 'Pickle'), ('BS', 'Bangladeshi Snacks')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_pr_price',
            field=models.CharField(max_length=1),
        ),
    ]
